<?php

return [
    'title' => 'Sobre nosotros',
    'label' => 'El Centro de Preparación Savo',
    'description1' => 'comenzó sus operaciones en 2021 como centro de preparación de Amazon. Está ubicado en Indianápolis, EE. UU., y es responsable de recibir, inspeccionar y preparar los productos cumpliendo con los estrictos estándares de preparación de Amazon. Vamos a sumergirnos en más información. Contamos con un equipo altamente capacitado que trabaja las 24 horas del día para asegurarse de que los pedidos se cumplan de manera rápida y eficiente. Tenemos la experiencia y el conocimiento para brindar el mejor servicio de calidad. Disponemos de todos los equipos y herramientas necesarias para ser un centro de preparación especializado en este servicio.',
    'description2' => 'Ahora vamos a sumergirnos en los estándares. Tenemos un gran almacén donde sus productos estarán en las mejores manos. Nuestro almacén está controlado en términos de temperatura y humedad para garantizar que sus productos se almacenen en las mejores condiciones posibles. También tenemos un sistema de seguridad para proteger sus productos de robos o daños. Nos enorgullece ofrecer un almacén profesional con un amplio espacio para los productos. Esto nos permite organizar el almacenamiento y procesar rápidamente los envíos entrantes. Tenemos una variedad de opciones de envío disponibles y podemos satisfacer la mayoría de las solicitudes de los clientes. Mientras tanto, nuestro equipo tiene experiencia y está dedicado a brindar el mejor servicio posible. Si te preocupa el tiempo que dedicas a preparar tu inventario, no te preocupes.
    Déjalo en manos de los expertos. Tenemos las herramientas y la experiencia para hacer el trabajo de manera rápida y eficiente. Además, podemos ayudarte a ahorrar dinero en costos de inventario. Nuestra misión como Centro de Preparación de Amazon es proporcionarte las mejores herramientas y productos de calidad para ayudarte a alcanzar un nivel profesional de éxito con tu negocio FBA y FBM.',
    'Frequently asked questions' => 'Preguntas frecuentes',
    'faq_question1' => '¿Cómo funciona el centro de preparación de Savo?',
    'faq_answer1' => 'En la página www.savoprep.com, simplemente haz clic en la pestaña "Registro" en la parte superior de la pantalla y envía tu nombre, ubicación, nombre de la empresa, tipo de servicio y otra información requerida en el formulario, y responderemos con toda la información relevante que necesitas saber. También puedes hacer clic en el tipo de servicio correspondiente en la parte superior de la pantalla para tener una idea de los servicios incluidos y sus precios.',

    'faq_question2' => '¿Qué tan rápido se preparan y envían los pedidos de Amazon?',
    'faq_answer2' => 'En la página www.savoprep.com, simplemente haz clic en la pestaña "Registro" en la parte superior de la pantalla y envía tu nombre, ubicación, nombre de la empresa, tipo de servicio y otra información requerida en el formulario, y responderemos con toda la información relevante que necesitas saber. También puedes hacer clic en el tipo de servicio correspondiente en la parte superior de la pantalla para tener una idea de los servicios incluidos y sus precios.',

    'faq_question3' => '¿Está SavoPrep cerca de los almacenes de Amazon?',
    'faq_answer3' => 'En la página www.savoprep.com, simplemente haz clic en la pestaña "Registro" en la parte superior de la pantalla y envía tu nombre, ubicación, nombre de la empresa, tipo de servicio y otra información requerida en el formulario, y responderemos con toda la información relevante que necesitas saber. También puedes hacer clic en el tipo de servicio correspondiente en la parte superior de la pantalla para tener una idea de los servicios incluidos y sus precios.',

    'faq_question4' => '¿Seleccionan los tipos de pedidos que aceptan?',
    'faq_answer4' => 'En la página www.savoprep.com, simplemente haz clic en la pestaña "Registro" en la parte superior de la pantalla y envía tu nombre, ubicación, nombre de la empresa, tipo de servicio y otra información requerida en el formulario, y responderemos con toda la información relevante que necesitas saber. También puedes hacer clic en el tipo de servicio correspondiente en la parte superior de la pantalla para tener una idea de los servicios incluidos y sus precios.',

    'faq_question5' => '¿Aceptan arbitraje minorista y en línea?',
    'faq_answer5' => 'En la página www.savoprep.com, simplemente haz clic en la pestaña "Registro" en la parte superior de la pantalla y envía tu nombre, ubicación, nombre de la empresa, tipo de servicio y otra información requerida en el formulario, y responderemos con toda la información relevante que necesitas saber. También puedes hacer clic en el tipo de servicio correspondiente en la parte superior de la pantalla para tener una idea de los servicios incluidos y sus precios.',

    'faq_question6' => '¿Ofrecen servicios de almacenamiento?',
    'faq_answer6' => 'En la página www.savoprep.com, simplemente haz clic en la pestaña "Registro" en la parte superior de la pantalla y envía tu nombre, ubicación, nombre de la empresa, tipo de servicio y otra información requerida en el formulario, y responderemos con toda la información relevante que necesitas saber. También puedes hacer clic en el tipo de servicio correspondiente en la parte superior de la pantalla para tener una idea de los servicios incluidos y sus precios.',
];
